### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by ghost** [MherZaqaryan/BedWars1058-Private-Games#1]
The privategame menu item doesnt work :(

**Comment by reussy** [comment]
**Preview in multi-arena:** https://youtu.be/fNkVBMzAdwQ

**Comment by MherZaqaryan** [comment]
I need more information about your server like
Software, software version, bedwars1058 version

**Comment by reussy** [comment]
Software: Spigot but I tried in Paper and same problem
Version: 1.8.8
BW1058: I tried 21.9.2 and 21.10.1

I tried without other stuff, only BW1058 and Private Games

**Comment by MherZaqaryan** [comment]
This issue is fixed on the new version 1.1.1!
Download it from here: https://polymart.org/resource/bedwars1058-private-games-addon.1620
