### ISSUE TITLE
PickAxe/Axe gets duped on respawn...

### ISSUE THREAD

**Issue by palash-08** [MherZaqaryan/BedWars1058-Private-Games#10]
1. Whenever you enter a Match, and purchase an axe/pickaxe from the in-game shop, they are meant to be in your inventory even after death, but 1 level lower of its previous upgrade level.

2. When you do this in a private match, basically keepInventory is set to true, this causes issues, because you eventually get 2 of them (the tools you purchased) in your inventory, one is of the same level which you have before death, and the another one is 1 level lower of the one you had before death (the second one is intentional)

3. This causes a mess for players, as their inventories just keep getting filled up with stuff that cannot be thrown!

Running:
- PaperSpigot v. 1.8.8
- Bedwars1058 v. 21.10
- PrivateGames v. 1.1.2

**Comment by MherZaqaryan** [comment]
Hey, as far as I understood you get your old stuff from inventory when you re-spawn and it's basically because you have keep inventory to true, if you disable it should work it's not an issue from Private Games
