### ISSUE TITLE
Heart and kill problem

### ISSUE THREAD

**Issue by TeruHUB** [MherZaqaryan/BedWars1058-Private-Games#11]
if i create private and i quit before the ending of games, i have problem i 60earth and kill me in lobby. please help me :D

**Comment by MherZaqaryan** [comment]
Hey, are you using BUNGEE mode for BedWars1058?

**Comment by TeruHUB** [comment]
no, i use multiarena

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available in the next update!
