### ISSUE TITLE
Issue when using /private settings

### ISSUE THREAD

**Issue by Pro-Nil** [MherZaqaryan/BedWars1058-Private-Games#13]
**Describe the bug**
Whenever the command /private settings is execute is posts an error 

pastebin link to the error :
https://pastebin.com/7rx0LUzm

**How to reproduce**
1. Create A Party
2. Use /private
3. Then use /private settings

**Screenshots**
screenshots , idk what to give regarding it , pastebin link https://pastebin.com/7rx0LUzm

**Server Information (please complete the following information):**
 - OS: [Linux / pterodactyl panel]
 - Server Software: [Paper]
 - Software Version: [1.8.9]
 - BedWars1058 Version: [21.11.1]
 - Private Games Addon: [1.1.3]

**Comment by MherZaqaryan** [comment]
This issue is fixed and will be available on the next update!
