### ISSUE TITLE
Error on Java 16/Java 17

### ISSUE THREAD

**Issue by Askarionn** [MherZaqaryan/BedWars1058-Private-Games#14]
**Describe the bug**
Error on Java 17

**How to reproduce**
1. Use java 17
2. You will get the error

**Screenshots**
https://pastebin.com/Xdnr7pDS

**Server Information (please complete the following information):**
 - OS: Debian 11
 - Server Software: NachoSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: BedWarsProxy 1.2.4
 - Private Games Addon: 1.1.3

**Additional context**
-

**Comment by MherZaqaryan** [comment]
Issue fixed, download it from here https://polymart.org/resource/1620
