### ISSUE TITLE
private games

### ISSUE THREAD

**Issue by akillamrck** [MherZaqaryan/BedWars1058-Private-Games#17]
**Describe the bug**
I want to put a command to the item back of the private games but I cannot try to put the same command that I use in the miencraft server and it does not work

**Screenshots**

 - OS: [Linux]
 - Server Software: [Paper]
 - Software Version: [1.8.9]
 - BedWars1058 Version: [21.10.1]
 - Private Games Addon: [1.1.1]

**Comment by MherZaqaryan** [comment]
I've reviewed this issue, and it was false, please make sure to put the command on the `command` section without a slash, I tested it with `help` command and it works perfect, remember that this command is being executed by the current player
![image](https://user-images.githubusercontent.com/64862924/150223010-cd69e299-19d2-4526-ae8c-eb4c411d9e63.png)
