### ISSUE TITLE
Error on proxy mode

### ISSUE THREAD

**Issue by Askarionn** [MherZaqaryan/BedWars1058-Private-Games#2]
Error: https://pastebin.com/kjwk8ngh
I don't know how to reproduce it i just saw it on console
Server version: 1.8.8
Plugin version: 1.1.0
Java version: 11

**Comment by MherZaqaryan** [comment]
This issue is fixed on the new version 1.1.1!
Download it from here: https://polymart.org/resource/bedwars1058-private-games-addon.1620
