### ISSUE TITLE
Private Games Joining issues

### ISSUE THREAD

**Issue by Pro-Nil** [MherZaqaryan/BedWars1058-Private-Games#20]
**Describe the bug**
Issue with game joining logics

**How to reproduce**
1. Player x creates a party and invites his friends to the party and enables private game 
2. Now let there be a player y who has already joined a map called Amazon .
3. The Player x and his friends join the same map called amazon in which player y  (who is not a part of the party)  is in.
4. Thus , then that arena becomes a private game arena and nobody else can join then .

**Screenshots**

**Server Information (please complete the following information):**
 - OS: PteroDactyl Panel
 - Server Software: Paper 1.8.8
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.2
 - Private Games Addon: 1.1.5
 - Java version : 8

**Additional context**

**Comment by MherZaqaryan** [comment]
I would really appreciate it if you provide some short videos about it so I can understand the issue more clear, also what's your server type (bungee, multiarena, etc.)

**Comment by MherZaqaryan** [comment]
#19

**Comment by Pro-Nil** [comment]
> I would really appreciate it if you provide some short videos about it so I can understand the issue more clear, also what's your server type (bungee, multiarena, etc.)

Server type is multi arena .
I will record a video and send tomorrow.

**Comment by Pro-Nil** [comment]
Video of the bug :
https://www.youtube.com/watch?v=MYJjg3OEi30

**Comment by MherZaqaryan** [comment]
This issue is fixed, and will be available on the next update!
