### ISSUE TITLE
Issue with /private settings (bw proxy)

### ISSUE THREAD

**Issue by Pro-Nil** [MherZaqaryan/BedWars1058-Private-Games#21]
**Describe the bug**
Issue with /private settings (bw proxy)

**How to reproduce**
1. Create party
2. enable private games
3. use /private settings and you get the error

**Error Log**
https://pastebin.com/7FEKybvp

**Server Information :**
 - OS: [Pterodactyl]
 - Server Software: [Paper]
 - Software Version: [1.8.8]
 - BedWars1058 Version: [22.2]
 - Private Games Addon: [1.1.5]

**Additional context**

**Comment by MherZaqaryan** [comment]
Thank you for reporting, i'll look into it as soon as possible

**Comment by MherZaqaryan** [comment]
This issue is already fixed and it shall be available on the next update!
