### ISSUE TITLE
Issue when there is two arena servers

### ISSUE THREAD

**Issue by MoGGaming** [MherZaqaryan/BedWars1058-Private-Games#22]
I'm having issues setting up private games in bungee mode, it's all good when only one of my arena servers is running but breaks as soon as I start both of my arena servers:

This is the configuration I have:
Bwhub (with Bedwars Proxy): different port other than BedWarsProxy's for Private Games
Bw2
Bw1 

This works:
bwhub (online 🟢 )
bw2 (online 🟢 )
bw1 (offline 🔴 )

This doesn't:
bwhub (online 🟢 )
bw2 (online 🟢 )
bw1 (online 🟢 ) 

**Server Information (please complete the following information):**
 - Server Software: Paper
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.2
 - Private Games Addon: 1.1.5
 
**Additional context**
Make it so it works even if I have more than 2 arena servers on

**Comment by MherZaqaryan** [comment]
This issue is already fixed and should be available in the next update!
