### ISSUE TITLE
Alternative way to join a private game

### ISSUE THREAD

**Issue by Propants05** [MherZaqaryan/BedWars1058-Private-Games#25]
you could put that with an option who created the private game has the possibility to activate the command / join name or to use it with the party?

**Comment by MherZaqaryan** [comment]
Hey, that could be possible, I will be considered this in the next updates!

**Comment by Propants05** [comment]
thanks you <3

**Comment by MherZaqaryan** [comment]
This enchantment has been rejected, after thinking about the implementation ways, this feature has to be implemented on some specific party plugin that has this feature built-in, so basically, that particular party plugin has to have a feature that will let party owners turn on something like public mode, and with this other people could join with running something like `/party join <username>` command, if you have found any party plugin that has this feature I can probably add support for BedWars1058 and BedWarsProxy.
