### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Pro-Nil** [MherZaqaryan/BedWars1058-Private-Games#27]
**Describe the bug**
Error on startup

**How to reproduce**
1. Put the version 1.1.6 of priv games
2. Then restart
3. Result : https://pastebin.com/rTcBSpBP

**Error Log**
https://pastebin.com/rTcBSpBP

**Server Information :**
 - OS: PteroDactyl Panel
 - Server Software: Carbon Spigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.2
 - Private Games Addon: 1.1.6

**Additional context**

**Comment by MherZaqaryan** [comment]
This issue is already fixed!
