### ISSUE TITLE
/private cmd issue

### ISSUE THREAD

**Issue by Pro-Nil** [MherZaqaryan/BedWars1058-Private-Games#28]
**Describe the bug**
/private doesnt work

**How to reproduce**
1. create party
2. use /party
3. Will result in https://pastebin.com/8PmbdDXw

**Error Log**
https://pastebin.com/8PmbdDXw

**Server Information (please complete the following information):**
 - OS: Pterodactyl panel
 - Server Software: CarbonSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.2
 - Private Games Addon: 1.1.6

**Comment by MherZaqaryan** [comment]
This issue is already fixed and should be available on the next update!
