### ISSUE TITLE
/private cmd not work (MultiArena)

### ISSUE THREAD

**Issue by Xxyuri2005xX** [MherZaqaryan/BedWars1058-Private-Games#29]
**Describe the bug**
Private cmd not eorking when is typed on a multiarena bedwars server

**How to reproduce**
1. Create a party
2. Invite friends
3. Type /private or other private cmds
4. Error in game & in console

**Screenshots**

**Server Information (please complete the following information):**
 - OS: IDK
 - Server Software: Spigot
 - Software Version: 1.8?8
 - BedWars1058 Version: 22.2
 - Private Games Addon: 1.1.6

**Additional context**
Console error link:
https://pastebin.com/0BjnC6zA

Error in game to player: 
"an internal error eccured while executing this command"

**Comment by MherZaqaryan** [comment]
#28
