### ISSUE TITLE
Damage after privategames

### ISSUE THREAD

**Issue by ghost** [MherZaqaryan/BedWars1058-Private-Games#3]
In privategames (Multiarena mode)
After the private game player keeps dying from damage in lobby.
server software : Foxspigot 1.8.8

**Comment by MherZaqaryan** [comment]
it does not damage just a small issue about max health changing, this usually happens when the last game was private and max health modified there, this issue should be fixed on the next update!

**Comment by ghost** [comment]
Okayy thanks is it possible to disable the health thing?

**Comment by MherZaqaryan** [comment]
This issue is fixed, it should be available on next update
