### ISSUE TITLE
Disable Block Protection can't be disabled

### ISSUE THREAD

**Issue by GyroGyro** [MherZaqaryan/BedWars1058-Private-Games#30]
**Describe the bug**
The "disable block protection" item is not removed from the settings GUI when you set the modifier to false.

**How to reproduce**
Go to the config and in the Modifiers section set the "disable block protection" to false

**Screenshots**
https://imgur.com/dbVncNm.png
https://imgur.com/zO5dKnJ.png

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: Paper
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.2
 - Private Games Addon: 1.1.7 beta

**Comment by MherZaqaryan** [comment]
This issue is already fixed and shall be available on the next update!
