### ISSUE TITLE
private games is stuck

### ISSUE THREAD

**Issue by Stefan344** [MherZaqaryan/BedWars1058-Private-Games#31]
**Describe the bug**
Server doesnt want to load private games
**How to reproduce**
1. put the plugin in the server
2. restart the server
3. will result plugin stucking

**Screenshots**
https://i.upload.systems/lunox/TtIS417K

**Server Information (please complete the following information):**
 - OS: [Windows]
 - Server Software:  [Spigot]
 - Software Version: [1.8.8]
 - BedWars1058 Version: [22.2]
 - Private Games Addon: [1.1.6 and 1.1.7-BETA]

**Additional context**
the bedwars plugin is in MULTIARENA mode

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available on the next update!
