### ISSUE TITLE
Low gravity modifier issue

### ISSUE THREAD

**Issue by Pro-Nil** [MherZaqaryan/BedWars1058-Private-Games#32]
**Describe the bug**
Low gravity modifier issue

**How to reproduce**
1. Enable low gravity modifier
2. Go ingame and buy jump potion
3. When the potion expires , you dont get low gravity effect back

**Server Information (please complete the following information):**
 - OS: Pterodactyl Panel
 - Server Software: CarbonSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.2
 - Private Games Addon: 1.1.7 Beta

**Comment by MherZaqaryan** [comment]
This issue is already fixed with also Speed modifier fix, and will be available in the next update!
