### ISSUE TITLE
Message for private games (Server Operators)

### ISSUE THREAD

**Issue by Pro-Nil** [MherZaqaryan/BedWars1058-Private-Games#36]
**Is your feature request related to a problem? Please describe.**
When players , make private games , and enter a arena , the arena starts , now on seeing arena starting , say a server op joins the game . He / she gets into a private game of the players . So players are like , why did you join a private game 🤣 .

**Describe the solution you'd like**
When a server op joins a private games , send him / here a message -> You have joined a private game . / prevent server op from joining the game .

**Describe alternatives you've considered**
Being very alert 😆

**Comment by MherZaqaryan** [comment]
Hey, thank you for the request, so what you are trying to say is to let or prevent OPs from joining a private arena.
I've tested myself and saw that even when I am OP it doesn't let me join a private arena that is in starting state.
