### ISSUE TITLE
Add an option to don't start game alone

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Private-Games#37]
After test, i've see that the players can join and start a game alone
So i want to add an option to start the game only if there are at least 2 players minimum.
Like that, the players will never start a private games alone (which currently can distort the statistics)

Thanks in advance

**Comment by MherZaqaryan** [comment]
This feature should be implemented in the next updates!

**Comment by MherZaqaryan** [comment]
This feature request has already been implemented and will be available in the next update!
