### ISSUE TITLE
Party leader getting kick from arena server

### ISSUE THREAD

**Issue by MoGGaming** [MherZaqaryan/BedWars1058-Private-Games#38]
created party in bedwarlobby and pg enable
And when I click on random join
only pg creater(party leader)
getting kicked from server

[18:32:06 INFO]: MoG_Gaming lost connection: §cSorry but you must join an arena using BedWarsProxy. 
§eIf you want to setup an arena make sure to give yourself the bw.setup permission so you can join the server directly!

**Comment by MherZaqaryan** [comment]
#43
