### ISSUE TITLE
Feature Toggle

### ISSUE THREAD

**Issue by Seatch** [MherZaqaryan/BedWars1058-Private-Games#4]
So like in other plugins, there should be a 

enabled = true/false

what I want this for is to disable certain features from private games when i want them to. Like if I set it to, enabled = false under health, then the players won't be able to change the health.

**Comment by MherZaqaryan** [comment]
This feature should be implemented on the next update!

**Comment by MherZaqaryan** [comment]
This feature should be implemented on the next update!
