### ISSUE TITLE
the plugin "Reward Commands fo BedWars1058" also works during Private Games.

### ISSUE THREAD

**Issue by GyroGyro** [MherZaqaryan/BedWars1058-Private-Games#40]
**Describe the bug**
During Private Games the cmd-rewards plugins such as https://www.spigotmc.org/resources/addon-reward-commands-for-bedwars1058.55381/ should not execute the reward commands.
Players could take advantage of this "bug" to boost themselves without playing classic games

**How to reproduce**
1. install plugin cmd-rewards and restart,
2. start a private game 
3. you will be given a rewards when you destroy a bed, make a kill / final kill or when you win the game.

**Server Information (Important):**
 - Operating System: Linux
 - Server Software: Paper
 - Java Version:  8
 - Software Version: 1.8.8
 - Private Games Version: 1.1.7
 - BedWars1058 Version: 22.2
 - BedWars1058 Server Type: MULTIARENA

**Comment by MherZaqaryan** [comment]
This issue is fixed by having a custom-made RewardCMD. https://github.com/JT122406/bedwars1058-rewardcmdsPrivateGames
