### ISSUE TITLE
Minimum player amount

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Private-Games#41]
I would like an option on the plugin to set the minimum amount of players to start the game
Because i have network with one server per map
Per exemple, i want to set the minimum amount of players for solo on 2
The minimum amount of players for doubles on 4
The minimum amount of players for 3v3v3v3 on 6
And the minimum amount of players for 4v4v4v4 on 8

Like this, the server administrator which want the plugin like it is actually can leave the basic configuration and the server administrator like me which want to set custom minimum amount of players can set it !

Thanks in advance

**Comment by MherZaqaryan** [comment]
This feature request is accepted.

**Comment by MherZaqaryan** [comment]
#37
