### ISSUE TITLE
Heart amount isn't reset after private games

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Private-Games#42]
**Describe the bug**
After  a game with private games, i've join a normal game, without private games and my heart amount that was set on 3x in the last game haven't been reset on the normal game

**How to reproduce**
1. Play a game with Heart Modifier
2. End game
3. Play a normal game (not a private game)
4. Look at the amount of hearts

**Screenshots**
![unknown](https://user-images.githubusercontent.com/99984955/160007758-27bd8b99-5034-418e-aee9-6070a0bc1662.png)m.

**Server Information (Important):**
 - Operating System: Debian 10
 - Spigot
 - Java Version: 8
 - Software Version: 1.8.8
 - Private Games Version: 1.1.7
 - BedWars1058 Version: 22.2
 - BedWars1058 Server Type: Bungee
###

**Comment by MherZaqaryan** [comment]
This issue has been already fixed and will be available in the next update
