### ISSUE TITLE
Private games not working as expected in BUNGEE mode servers

### ISSUE THREAD

**Issue by Alijkaz** [MherZaqaryan/BedWars1058-Private-Games#43]
**Describe the bug**
I'm using BedWars1058 22.2 and Parties 3.1.14, Bungee mode
Tried installing and setting up PrivateGames going through the documentations steps,
It seems to be fine in lobby since I can invite players to my party and /pg /pg settings would work, but when we get in the game, none of the settings that I applied in /pg settings are working (and I see no difference in the scoreboard of privategames rather than normal games), also players across network will not be able to do `/bw join arenaGroup` (lets say Duo) for a random join as it says you can't join the specified game until the game is started (seems that BedwarsProxy is selecting the exact arena as it's in waiting stage and it seems the best choice, but PrivateGames is denying joining it)

**How to reproduce**
1. Setup a Bedwars1058(latest) bungee mode network
2. Install and configure PrivateGames on all lobby and game servers 
3. Invite a player in one the lobbies to your party
4. Configuring privategames with `/pg settings` and join a match
5. You'd see that arenagroup random join is not available until the game is started, and everything is as a usual match in the arena, no scoreboard indications saying its a private game and no custom settings applied

**Server Information (Important):**
 - Operating System: Linux
 - Server Software: Paper
 - Java Version: 17
 - Software Version: 1.8.8
 - Private Games Version: 1.1.7
 - BedWars1058 Version: tried both 22.3.4 and 22.2
 - BedWars1058 Server Type: BUNGEE

**Comment by MherZaqaryan** [comment]
This issue has been fixed with over 10/10 passed tests in a row and gladfully works perfectly.

NOTE: This fix requires a small change on BedWarsProxy. Please join my [Discord](https://mher.club/discord) to get it.
