### ISSUE TITLE
Match does not reset countdown after a player leaves, and starts with only 1 player.

### ISSUE THREAD

**Issue by Weark** [MherZaqaryan/BedWars1058-Private-Games#44]
**Describe the bug**
When we have private mode activated, and a player leaves the room with it starting, the count is not paused.

https://cdn.discordapp.com/attachments/973812768937500722/975520618634170458/Minecraft__1.17.1_-_Multiplayer_3rd-party_Server_15-05-2022_19-09-38.mp4

**How to reproduce**
1. Create a party and invite a player
2. Activate /private
3. Enter a room that starts with at least 2 players.
4. When the countdown begins, ask your friend to leave the room.
5. Therefore the countdown is not reset.
6. The match will start with just you.

**Screenshots**

**Server Information (Important):**
 - Operating System: Linux
 - Server Software: iSpigot
 - Java Version: 11
 - Software Version: 1.8.8
 - Private Games Version: 1.1.7
 - BedWars1058 Version: 22.3.4
 - BedWars1058 Server Type: MULTIARENA

**Comment by MherZaqaryan** [comment]
This issue is already fixed and must be available in the next update!

**Comment by Weark** [comment]
Ok, thanks.
