### ISSUE TITLE
Disable Shop Items Modifier

### ISSUE THREAD

**Issue by Xxyuri2005xX** [MherZaqaryan/BedWars1058-Private-Games#45]
**Is your feature request related to a problem? Please describe.**
With Private Games addon you can customize a lot of things for creating an incredible game with your friends.

**Describe the solution you'd like**
Adding an option for disabling some items (chosen by you) via the private modifiers menu, that opens the bw1058 shop gui and clicking intrested items, they got disabled for the PG.

**Describe alternatives you've considered**

**Additional context**

**Comment by MherZaqaryan** [comment]
Hey, please give more information about this enchantment.

**Comment by Xxyuri2005xX** [comment]
you can disable some items from the shop, like:
if the private game owner doesn't want bows in its game he can disable them with like the quickbuy menu

**Comment by MherZaqaryan** [comment]
This feature isn't possible, there is currently no way to disable shop items for specific arenas.
