### ISSUE TITLE
Game doesn't end

### ISSUE THREAD

**Issue by kimoVoid** [MherZaqaryan/BedWars1058-Private-Games#47]
**Describe the bug**
In a private game (only tested with 2 players so far), when the leader leaves the game, the game doesn't end. Instead, it goes into waiting mode, and it behaves weird.

**How to reproduce**
1. Create a party with 2 players
2. Enable private game
3. Join a game and use /bw start debug
4. Make the leader quit the game
5. The game will now be in waiting mode instead of ending

**Screenshots**
![2022-08-24_18 45 19](https://user-images.githubusercontent.com/29529059/186529263-33d537f1-97a1-4317-8dbb-0435d98e68b7.png)

**Server Information (Important):**
 - Operating System: Debian 10
 - Server Software: NachoSpigot 1.8.8 (Paper fork)
 - Java Version: 8
 - Software Version: 1.8.8
 - Private Games Version: 1.1.8-HOTFIX
 - BedWars1058 Version: 22.3.4
 - BedWars1058 Server Type: BUNGEE

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available in the next update!
