### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Private-Games#48]
**Describe the bug**
The coutdown won't start when joining a private games

**How to reproduce**
1. Create a party with multiple players
2. Do /pg to enable private games
3. Join an arena with pg enabled
4. The coutdown won't start so the party will never start

**Screenshots**

**Server Information (Important):**
 - Operating System: Debian
 - Server Software: Paper
 - Java Version: 8
 - Software Version: 1.8.8
 - Private Games Version: 1.1.8 HOTFIX
 - BedWars1058 Version: Latest
 - BedWars1058 Server Type: BUNGEE

**Comment by MherZaqaryan** [comment]
This issue has been fixed and will be available in the next update!
