### ISSUE TITLE
shakiz- team selector with spectate mode

### ISSUE THREAD

**Issue by shakizwastaken** [MherZaqaryan/BedWars1058-Private-Games#5]
**Describe the solution you'd like**

**hey can you please add a team selector that's only with private games with spectate mode on it**
like hypixel's

**Comment by MherZaqaryan** [comment]
Seems like there is already an addon for that https://www.spigotmc.org/resources/addon-team-selector-for-bedwars1058.60438/

**Comment by shakizwastaken** [comment]
> Seems like there is already an addon for that https://www.spigotmc.org/resources/addon-team-selector-for-bedwars1058.60438/

the addon that you showed me is half broken and works on all games (not just private games) which isnt good

**Comment by MherZaqaryan** [comment]
I'll try to do add support for the team selector addon in the future but at the moment I can't implement the Team Selector addon in the Private Games addon!
