### ISSUE TITLE
Normal players can join PrivateGames of other players even if they aren't in their party

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Private-Games#51]
**Describe the bug**
The players which are on my server to play basic Bedwars game can join the PrivateGames of other players but they aren't in their party

**How to reproduce**
1. Take 3 players and one map (per exemple, gamecube map)
2. With two players, create a party (using PAF system) with /party invite <the second player>
3. Do a /pg to enable the private games
4. Join the gamecube map (in my case, i'm using /bw join gamecube)
5. You will be with your second account in a private game cause you have the private games item in your hotbar
6. With the third account, do a /bw join gamecube
7. The third account will be in the private games of the 2 other players but he's  not in their party
8. Start the game, the 3 players will be in a private games with only 2 people in the /party

**Server Information (Important):**
 - Operating System: Debian
 - Server Software: Paper
 - Java Version:  8
 - Software Version: 1.8.8
 - Private Games Version: 1.1.9
 - BedWars1058 Server Type: BUNGEE

**Comment by MherZaqaryan** [comment]
This issue has been fixed, and will be available in the next update!
