### ISSUE TITLE
Problems, with Bungee Mode

### ISSUE THREAD

**Issue by TeruHUB** [MherZaqaryan/BedWars1058-Private-Games#52]
**Describe the bug**
like in proxy mode, my friend join party, when made /private tell me every time "enable" not one enable and disable, i can't disable, and when i joined the game "private enabled" i don't have the item for settings and don't start because is normal game (ports and sockets are correct and open)

**How to reproduce**
1. Invite friend in party
2. /private and that will show you always "enabled" and never "disabled" you can't disable 
3. when you are in game (sockets opens end works) you don't have the private games items for all settings, don't start, because this is a normal game.

**Screenshots**
https://imgur.com/IlM1p3O always show enabled 
https://imgur.com/TdGDuOp game don't have items

**Server Information (Important):**
 - Operating System: Linux
 - Server Software: FoxSpigot (paper)
 - Java Version: 8
 - Software Version: 1.8.8
 - Private Games Version: Beta Version
 - BedWars1058 Version: Latest and custom, but never touch sockets etc..
 - BedWars1058 Server Type: BUNGEE

**Comment by haroldrc** [comment]
same problem

**Comment by MherZaqaryan** [comment]
This issue has been fixed and will be available for the next update.
