### ISSUE TITLE
Party compatibility issues with PAF plugins

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Private-Games#59]
My server uses Bunge mode. When players join the game without of a party, the Lobby server will encounter the following error. If they in a party, it will be normal
https://pastebin.com/Gg0fWY9s

**Comment by MherZaqaryan** [comment]
This is a BedWarsProxy issue, even tho it shows `Could not pass event PlayerArenaJoinEvent to BedWars1058-PrivateGames v1.1.10` it isn't a Private Games issue. Private Games doesn't handle BedWarsProxy party compatibilities, everything is handled by BedWarsProxy. Please report this to BedWarsProxy GitHub instead!
