### ISSUE TITLE
Problem with only one map in Bunge Mode

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Private-Games#61]
I have a bedwars mode with only one map, it with auto-scale true in bungee mode. However, I have found that if a player plays a private game on this only map, other players will not be able to join this mode and auto scale will not be able to create new arenas until this private game starts.

**Comment by MherZaqaryan** [comment]
This is not a bug, BedWars1058 works like that, if you want to have enough arenas available for players to play just have your arena cloned.
