### ISSUE TITLE
Non Party Members joining the party

### ISSUE THREAD

**Issue by SameshB** [MherZaqaryan/BedWars1058-Private-Games#65]
**Describe the bug**
Non party members are able to join the party

**How to reproduce**
1. You need atleast 3 players
2. Create a party of 2 members and enable private games
3. Join a Bedwars arena
4. Enter the same arena with a non-party member
5. Non party member will be able to join

**Server Information (Important):**
 - Server Software: Carbon
 - Java Version: 11
 - Software Version: 1.8.8
 - Private Games Version: 1.1.9
 - BedWars1058 Version: 23.3
 - BedWars1058 Server Type: MULTIARENA

**Comment by MherZaqaryan** [comment]
This issue is fixed, and the fix will be available in the next update!
