### ISSUE TITLE
not lock games

### ISSUE THREAD

**Issue by amirhosein1000** [MherZaqaryan/BedWars1058-Private-Games#66]
not lock private games and all can join private games

Server Information:
 - Operating System: Linux
 - Server Software: Spigot
 - Java Version: 11
 - Software Version: 1.8.8
 - Private Games Version: 1.1.10
 - BedWars1058 Version: 23.3
 - BedWars1058 Server Type: MULTIARENA

**Comment by amirhosein1000** [comment]
https://cdn.discordapp.com/attachments/1185451475044937758/1188103077312593920/compress.mp4?ex=65994e37&is=6586d937&hm=026d42f944e0ee9847c416d2049dac68dbda9b358e6418c832e56695f48d283b&

**Comment by MherZaqaryan** [comment]
This issue is fixed, and the fix will be available in the next update!
