### ISSUE TITLE
Add function to disable private games in certain arena groups

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Private-Games#68]
**Is your feature request related to a problem? Please describe.**
There is no problem, but I would like to add it

**Describe the solution you'd like**
I would like to add a feature to the config to disable private games in certain arena groups.

**Describe alternatives you've considered**
I would like to add the function to disable private games in the config for certain arena groups.

**Comment by MherZaqaryan** [comment]
This feature request is accepted.

**Comment by MherZaqaryan** [comment]
This feature request has been implemented and will be available in the next update!
