### ISSUE TITLE
Priority Bug

### ISSUE THREAD

**Issue by Seatch** [MherZaqaryan/BedWars1058-Private-Games#7]
**Describe the bug**
Im partied with 2 other people, i do /private and join a match (randomly) where there are already 2 other people because matches that haven't started and have players in them take priority when auto joining a match. Once i joined, It turned the game to private and all players, party or not were affected. (MultiArena Mode)

**How to reproduce**
1. Firstly, you will need at least 3 people (im gonna call them man1, man2 and man3 for ease) and will have to set the server mode to MultiArena. Also, I'm gonna make the steps according to mher's test servers so the commands should be the same.
2. Tell man1 to join a match.
3. man2 and man3 should should be in 1 party. Once done, enable private games.
4. Now the party leader (man2 or man3) should do /bw join Solo, once the leader did this, naturally both man2 and man3 would join the match that man1 was in because that's how bedwars1058 map priority works.
5. Now, the normal min limit is 2 so the match would auto start countdown. Let the match start.

Result = Private game would get enabled for the partied players (man2 and man3) AND man1 who was NOT in the party.

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available on the next update, thank you for supporting!
