### ISSUE TITLE
Bug when disable block protection is turned on players can't break protected blocks.

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Private-Games#70]
There is a bug in version 1.20.4 where the disable block protection option does not work.

https://youtu.be/bKBc0UVZ4qM

**Server Information (Important):**
 - Operating System: [e.g. Linux, Windows, Mac] Windows
 - Server Software: [e.g. Paper, Spigot] Paper
 - Java Version: [e.g 8, 16, 17] 17
 - Software Version: [e.g. 1.8.8] 1.20.4
 - Private Games Version: [e.g. 1.1.7] 1.1.11
 - BedWars1058 Version: [e.g. 22.2] 23.2.1
 - BedWars1058 Server Type: [e.g. MULTIARENA, BUNGEE, SHARED] MULTIARENA

**Comment by MherZaqaryan** [comment]
This is not a 1.20.4 specific issue. It's a different issue related to protected areas in the arenas, like the spawn point, generators, etc.

**Comment by ImYenil** [comment]
> This is not a 1.20.4 specific issue. It's a different issue related to protected areas in the arenas, like the spawn point, generators, etc.

I only had BedWars1058 and BedWars1058-PrivateGames plugins.

**Comment by MherZaqaryan** [comment]
This issue is fixed, and the fix will be available in the next update.

**Comment by MherZaqaryan** [comment]
> > This is not a 1.20.4 specific issue. It's a different issue related to protected areas in the arenas, like the spawn point, generators, etc.
> 
> I only had BedWars1058 and BedWars1058-PrivateGames plugins.

Yes, those are BedWars1058 protected areas, check the arena file.

```yml
spawn-protection: 3
shop-protection: 1
upgrades-protection: 1
generator-protection: 1
```

**Comment by ImYenil** [comment]
> > > This is not a 1.20.4 specific issue. It's a different issue related to protected areas in the arenas, like the spawn point, generators, etc.
> > 
> > 
> > I only had BedWars1058 and BedWars1058-PrivateGames plugins.
> 
> Yes, those are BedWars1058 protected areas, check the arena file.
> 
> ```yaml
> spawn-protection: 3
> shop-protection: 1
> upgrades-protection: 1
> generator-protection: 1
> ```

spawn-protection: 3
shop-protection: 3
upgrades-protection: 3
generator-protection-radius: 4
generator-protection-max-y: 5
generator-protection-min-y: 2

**Comment by MherZaqaryan** [comment]
Yep! Those protections were interfering, but it is already fixed for the next update!
