### ISSUE TITLE
one hit one kill option does not work on first hit

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Private-Games#71]
**Describe the bug**
one hit one kill option does not work on first hit

https://youtu.be/pVWCcmT0wDs

**Server Information (Important):**
Operating System: [e.g. Linux, Windows, Mac] Windows
Server Software: [e.g. Paper, Spigot] Paper
Java Version: [e.g 8, 16, 17] 17
Software Version: [e.g. 1.8.8] 1.20.4
Private Games Version: [e.g. 1.1.7] 1.1.11
BedWars1058 Version: [e.g. 22.2] 23.2.1
BedWars1058 Server Type: [e.g. MULTIARENA, BUNGEE, SHARED] MULTIARENA

**Comment by MherZaqaryan** [comment]
This issue is fixed, and the fix will be available in the next update!
