### ISSUE TITLE
Index 11 out of bounds for length 0 Issue

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Private-Games#73]
**Describe the bug**
When setting the respawn time, there is an error with Index 11 out of bounds for length 0.

**Server Information (Important):**
 - Operating System: [e.g. Linux, Windows, Mac] Windows 
 - Server Software: [e.g. Paper, Spigot] Paper
 - Java Version: [e.g 8, 16, 17] 11 
 - Software Version: [e.g. 1.8.8] 1.8.8
 - Private Games Version: [e.g. 1.1.7] 1.2.0
 - BedWars1058 Version: [e.g. 22.2] 23.12.1-SNAPSHOT
 - BedWars1058 Server Type: [e.g. MULTIARENA, BUNGEE, SHARED] MULTIARENA

Error Log
https://pastebin.com/U19tuQEL

**Comment by MherZaqaryan** [comment]
This issue is invalid, there might be an issue with your configuration, please check your `config.yml` file for respawn-time menu settings and make sure you have `rows` set at least **2** for the **11th** slot to be available in the GUI, by default it's set to **4**.
