### ISSUE TITLE
Repost Bug when disable block protection is turned on players can't break protected blocks

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Private-Games#74]
Bug when disable block protection is turned on players can't break protected blocks

https://youtu.be/bKBc0UVZ4qM

Server Information (Important):

Operating System: [e.g. Linux, Windows, Mac] Windows
Server Software: [e.g. Paper, Spigot] Paper
Java Version: [e.g 8, 16, 17] 17
Software Version: [e.g. 1.8.8] 1.20.4
Private Games Version: [e.g. 1.1.7] 1.2.0
BedWars1058 Version: [e.g. 22.2] 23.2.1-SNAPSHOT
BedWars1058 Server Type: [e.g. MULTIARENA, BUNGEE, SHARED] MULTIARENA

I updated the plugin, but this bug still hasn't been fixed.

**Comment by ImYenil** [comment]
I will provide the code

@EventHandler
public void test(GameStateChangeEvent e) {
        if (Add code if disable block protection is enabled in private settings) {
            if (e.getArena().getConfig().getBoolean("allow-map-break")) {
                e.getArena().getConfig().set("allow-map-break", true);
            }
        } else {
            if (e.getArena().getConfig().getBoolean("allow-map-break")) {
                e.getArena().getConfig().set("allow-map-break", false);
            }
        }
    }

@EventHandler
public void onGameEnd(GameEndEvent e) {
        IArena a = e.getArena();
        if (a.getConfig().getBoolean("allow-map-break")) {
            a.getConfig().set("allow-map-break", false);
        }
}

**Comment by MherZaqaryan** [comment]
This issue is invalid, I have tried to reproduce it and I didn't have this issue, everything worked fine. The video that shows it, was posted on my Discord server.

For the next update, I made a minor change (not going to be listed in the change logs) that can probably fix the issue you have (possibly because you're using a little bit old version of BedWars1058 or a custom one)
