### ISSUE TITLE
There is a bug with the bed-instabreak option that breaks the my team bed.

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Private-Games#75]
**Describe the bug**
There is a bug with the bed-instabreak option that breaks the my team bed.

https://youtu.be/E0U6yBz2qFE

**Server Information (Important):**
 - Operating System: [e.g. Linux, Windows, Mac] Windows
 - Server Software: [e.g. Paper, Spigot] Paper
 - Java Version: [e.g 8, 16, 17] 11 
 - Software Version: [e.g. 1.8.8] 1.8.8
 - Private Games Version: [e.g. 1.1.7] 1.2.0
 - BedWars1058 Version: [e.g. 22.2] 23.12.1-SNAPSHOT
 - BedWars1058 Server Type: [e.g. MULTIARENA, BUNGEE, SHARED] MULTIARENA

**Comment by MherZaqaryan** [comment]
This issue is fixed and will be available in the next update!
