### ISSUE TITLE
Bug where setting respawn time and killing the player causes it to respawn at the player's location

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Private-Games#76]
**Describe the bug**
Bug where setting respawn time and killing the player causes it to respawn at the player's location

https://youtu.be/0v_G1IoI3WY

**Server Information (Important):**
Operating System: [e.g. Linux, Windows, Mac] Windows
Server Software: [e.g. Paper, Spigot] Paper
Java Version: [e.g 8, 16, 17] 11
Software Version: [e.g. 1.8.8] 1.8.8
Private Games Version: [e.g. 1.1.7] 1.2.0
BedWars1058 Version: [e.g. 22.2] 23.12.1-SNAPSHOT
BedWars1058 Server Type: [e.g. MULTIARENA, BUNGEE, SHARED] MULTIARENA

**Comment by MherZaqaryan** [comment]
This issue is invalid, I have tried to reproduce it and I didn't have this issue, everything worked fine. The video that shows it, was posted on my Discord server.
