### ISSUE TITLE
NullPointerException Issue

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Private-Games#77]
**Describe the bug**
I don't know when it will happen, but it will happen soon.

https://pastebin.com/j3Xjt0r5

**Server Information (Important):**
 - Operating System: [e.g. Linux, Windows, Mac] Windows
 - Server Software: [e.g. Paper, Spigot] Paper
 - Java Version: [e.g 8, 16, 17] 11
 - Software Version: [e.g. 1.8.8] 1.8.8
 - Private Games Version: [e.g. 1.1.7] 1.2.1
 - BedWars1058 Version: [e.g. 22.2] 23.2.1
 - BedWars1058 Server Type: [e.g. MULTIARENA, BUNGEE, SHARED] MULTIARENA

**Comment by MherZaqaryan** [comment]
This issue is fixed and will be available in the next update!

**Comment by ImYenil** [comment]
> This issue is fixed and will be available in the next update!

I'm using the new update but it's not fixed
